### ISSUE TITLE
Rename project to meet naming conventions

### ISSUE THREAD

**Issue by jhrabi** [Rishon73/AOS_TruClient_buy_headphones_with_transactions#3]
@panama69 Please rename this project to match naming conventions (all lower case, seperate words with dashes). This is also REALLY long name for checkout.

**Comment by panama69** [comment]
I will work with @Rishon73 to figure out a better name which will be a little shorter.  as a general rule, i am not too concerned about the length but I agree on the naming convention of all lower case, seperate works with dashes

I am also noticing there are other files that are generated by Vugen/Truclient that don't need to be under version control.

**Comment by Rishon73** [comment]
I'm okay with aos-mobile-tc
And @panama69 , I already removed a couple files (not committed yet), pretty sure there are more, let me know which ones and I'll add them to the .gitignore file

**Comment by jhrabi** [comment]
I've run the rename of the project to aos-mobile-tc
